# Generated by Django 4.2.11 on 2024-05-12 17:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), (
                    'intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=100)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('open', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending_Approval'), (
                    'approved', 'Approved'), ('rejected', 'Rejected')], default='pending_approval', max_length=100)),
                ('group_size', models.PositiveIntegerField(null=True, validators=[
                 django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(9)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Open Project',
                'verbose_name_plural': 'Open Projects',
                'db_table': 'open_project',
                'ordering': ['-post_date'],
            },
        ),
        migrations.CreateModel(
            name='OpenProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='tags', to='open_projects.openproject')),
            ],
            options={
                'verbose_name': 'Open Project Tag',
                'verbose_name_plural': 'Open Project Tags',
                'db_table': 'open_project_tag',
            },
        ),
        migrations.CreateModel(
            name='OpenProjectSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='saved_open_project', to='open_projects.openproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='saved_open_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Open Project Save',
                'verbose_name_plural': 'Open Project Saves',
                'db_table': 'open_project_save',
            },
        ),
    ]
