# Generated by Django 4.2.11 on 2024-05-07 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openproject',
            name='status',
        ),
    ]
