# Generated by Django 4.2.11 on 2024-05-12 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openproject',
            name='group_size',
            field=models.PositiveIntegerField(default=2, validators=[
                                              django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
