# Generated by Django 4.2.11 on 2024-05-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_projects', '0002_remove_openproject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='openproject',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending_Approval'), (
                'approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=100),
        ),
    ]
