# Generated by Django 4.2.11 on 2024-05-12 17:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('open_projects', '0002_alter_openproject_group_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openproject',
            name='group_size',
            field=models.PositiveIntegerField(null=True, validators=[
                                              django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.CreateModel(
            name='OpenProjectApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('joined', 'Joined'), (
                    'rejected', 'Rejected')], default='applied', max_length=100)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='applied_open_project', to='open_projects.openproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='applied_open_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Open Project Apply',
                'verbose_name_plural': 'Open Project Applies',
                'db_table': 'open_project_apply',
            },
        ),
    ]
