# Generated by Django 4.2.11 on 2024-05-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_projects', '0002_openproject_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openproject',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending_Approval'), (
                'approved', 'Approved'), ('rejected', 'Rejected')], default='pending_approval', max_length=100),
        ),
    ]
