# Generated by Django 4.2.11 on 2024-05-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_projects', '0003_alter_openproject_status'),
        ('open_projects', '0003_openproject_status'),
        ('open_projects', '0006_alter_openproject_user'),
    ]

    operations = [
    ]
