# Generated by Django 4.2.11 on 2024-05-12 17:11

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comment',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ShowcaseProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photos', django.contrib.postgres.fields.ArrayField(
                    base_field=models.URLField(), blank=True, default=list, size=None)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='posted_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Showcase Project',
                'verbose_name_plural': 'Showcase Projects',
                'db_table': 'showcase_project',
                'ordering': ['-post_date'],
            },
        ),
        migrations.CreateModel(
            name='ShowcaseProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='tags', to='showcase_projects.showcaseproject')),
            ],
            options={
                'verbose_name': 'Showcase Project Tag',
                'verbose_name_plural': 'Showcase Project Tags',
                'db_table': 'showcase_project_tag',
            },
        ),
        migrations.CreateModel(
            name='ShowcaseProjectSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='saved_showcase_project', to='showcase_projects.showcaseproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='saved_showcase_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Showcase Project Save',
                'verbose_name_plural': 'Showcase Project Saves',
                'db_table': 'showcase_project_save',
            },
        ),
        migrations.CreateModel(
            name='ShowcaseProjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('caption', models.CharField(max_length=250)),
                ('order', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='showcase_photos', to='showcase_projects.showcaseproject')),
            ],
            options={
                'verbose_name': 'Showcase Project Photo',
                'verbose_name_plural': 'Showcase Project Photos',
                'db_table': 'showcase_project_photo',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='liked_project', to='showcase_projects.showcaseproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='liked_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'db_table': 'like',
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='comment_likes', to='showcase_projects.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment Like',
                'verbose_name_plural': 'Comment Likes',
                'db_table': 'comment_like',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='comments', to='showcase_projects.showcaseproject'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
