# Generated by Django 4.2.11 on 2024-05-08 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseProjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('caption', models.CharField(max_length=250)),
                ('order', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='showcase_photos', to='showcase_projects.showcaseproject')),
            ],
            options={
                'verbose_name': 'Showcase Project Photo',
                'verbose_name_plural': 'Showcase Project Photos',
                'db_table': 'showcase_project_photo',
                'ordering': ['-order'],
            },
        ),
    ]
