# Generated by Django 4.2.11 on 2024-05-12 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_projects',
         '0002_remove_showcaseproject_photos_alter_like_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcaseprojectphoto',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='photos', to='showcase_projects.showcaseproject'),
        ),
    ]
