# Generated by Django 4.2.11 on 2024-05-12 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_projects', '0003_alter_showcaseprojectphoto_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='comment_likes', to='showcase_projects.comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='likes', to='showcase_projects.showcaseproject'),
        ),
    ]
