# Generated by Django 4.2.11 on 2024-05-19 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase_projects', '0004_alter_commentlike_comment_alter_like_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcaseproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='showcase_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
