# Generated by Django 4.2.11 on 2024-05-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_projects', '0002_showcaseprojectphoto'),
        ('showcase_projects', '0005_alter_showcaseproject_user'),
    ]

    operations = [
    ]
