# Generated by Django 4.2.11 on 2024-05-26 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_projects', '0006_merge_20240521_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcaseprojectphoto',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='photos', to='showcase_projects.showcaseproject'),
        ),
    ]
