# Generated by Django 4.2.11 on 2024-05-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='github',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='linkedin',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='major',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='profile_picture',
            field=models.ImageField(
                null=True, upload_to='profiles/profile_pics'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='resume',
            field=models.FileField(null=True, upload_to='profiles/resumes'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='school',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
