# Generated by Django 4.2.11 on 2024-05-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profiles_github_alter_profiles_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='school',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
