# Generated by Django 4.2.11 on 2024-05-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profiles_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='github',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='linkedin',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='major',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='profile_picture',
            field=models.ImageField(
                blank=True, upload_to='profiles/profile_pics'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='resume',
            field=models.FileField(blank=True, upload_to='profiles/resumes'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='school',
            field=models.CharField(max_length=100),
        ),
    ]
