# Generated by Django 4.2.11 on 2024-05-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profiles_bio_alter_profiles_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='github',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='linkedin',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='major',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='school',
            field=models.CharField(max_length=100),
        ),
    ]
