# Generated by Django 4.2.11 on 2024-05-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profiles_bio_alter_profiles_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='profile_picture',
            field=models.ImageField(
                blank=True, null=True, upload_to='profiles/profile_pics'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='resume',
            field=models.FileField(blank=True, null=True,
                                   upload_to='profiles/resumes'),
        ),
    ]
