# Generated by Django 4.2.11 on 2024-05-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profiles_bio_alter_profiles_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='github',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='major',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='school',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
